#!/usr/bin/env python

# Add containing folder to $PATH
import sys
import os
import json
import subprocess

file = sys.stdin.read()
projects_json = json.loads(open('data/projects.json', 'r').read())

def create_experience(job_type, name, location, time, description, technologies=None, **kwargs):
    description = description.replace('<br />', '}\n        \\item {').replace('%', '\\%')
    job_type = '{0} ({1})'.format(job_type, technologies) if technologies else job_type
    return """  \\cventry
    {{{0}}}
    {{{1}}}
    {{{2}}}
    {{{3}}}
    {{
      \\begin{{cvitems}}
        \\item {{{4}}}
      \\end{{cvitems}}
    }}

%---------------------------------------------------------\n""".format(job_type, name, location, time, description)

def create_projects(name, technologies, description, **kwargs):
    description = description.replace('<br />', '}\n      \\newline\n      \\skillsetstyle{').replace('%', '\\%')
    return """  \\cvproject
    {{{0}}}
    {{{1}}}
    {{
      \\skillsetstyle{{{2}}}
    }}\n""".format(name, technologies, description)

setup = {
    'experience': ("""\\cvsection{Experience}\n\\begin{cventries}\n""", """\end{cventries}"""),
    'projects': ("""\\cvsection{Projects}\n\\begin{cvprojects}\n""", """\end{cvprojects}""")
}
sections = ('experience', 'projects')
creation_templates = {
    'experience': create_experience,
    'projects': create_projects
}
files = {
    section: open('resume/resume/{}.tex'.format(section), 'w+') for section in sections
}
for section in sections:
    tex_file = files[section]
    creation_template = creation_templates[section]
    start, end = setup[section]
    tex_file.write(start)
    for project in projects_json:
        if 'resume-{}'.format(section) in project['pages']:
            tex_file.write(creation_template(**project))
    tex_file.write(end)

os.chdir('resume')
subprocess.Popen(['xelatex', 'JasonZukewichResume.tex'])
os.chdir('../')

print (file)

This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./JasonZukewichResume.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 22 language(s) loaded.
(./awesome-cv.cls
Document Class: awesome-cv 2017/02/05 v1.6.1 Awesome Curriculum Vitae Class
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tools/array.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/enumitem/enumitem.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/ms/ragged2e.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/ms/everysel.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics-def/xetex.def))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/xifthen/xifthen.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tools/calc.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/ifmtarg/ifmtarg.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/setspace/setspace.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/tuenc.def))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/unicode-math/unicode-math.st
y
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e
.sty) (/usr/local/texlive/2017basic/texmf-dist/tex/latex/ucharcat/ucharcat.sty)
 (/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/fix-cm.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/filehook/filehook.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/unicode-math/unicode-math-xe
tex.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/unicode-math/unicode-math-ta
ble.tex))) (./fontawesome.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/sourcesanspro/sourcesanspro.
sty (/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
 (/usr/local/texlive/2017basic/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/xkeyval/xkvutils.tex))))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-comm
on.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-comm
on-lists.tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-late
x.def (/usr/local/texlive/2017basic/texmf-dist/tex/latex/ms/everyshi.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.
tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
 (/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.cod
e.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code
.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfkeysfilte
red.code.tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-xet
ex.def
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-dvi
pdfmx.def
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-com
mon-pdf.def))))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoft
path.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprot
ocol.code.tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.cod
e.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.
tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.
tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathparser.cod
e.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
code.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
basic.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
trigonometric.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
random.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
comparison.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
base.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
round.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
misc.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
integerarithmetics.code.tex)))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code
.tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoin
ts.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
construct.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
usage.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescop
es.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregrap
hicstate.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretran
sformations.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequic
k.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobje
cts.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
processing.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearro
ws.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshad
e.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimag
e.code.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexte
rnal.code.tex))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelaye
rs.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretran
sparency.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatt
erns.code.tex)))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleshape
s.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.
code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-ve
rsion-0-65.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-ve
rsion-1-18.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/environ/environ.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tcolorbox/tcbskins.code.tex
Library (tcolorbox): 'tcbskins.code.tex' version '4.11'
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code
.tex)) (/usr/local/texlive/2017basic/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)
)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/utilities/pgffor.code.
tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)
))
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tik
z.code.tex
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/libraries/pgflibrarypl
othandlers.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/modules/pgfmodulematri
x.code.tex)
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/pgf/frontendlayer/tikz/lib
raries/tikzlibrarytopaths.code.tex)))
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/tcolorbox/tcbskinsjigsaw.cod
e.tex
Library (tcolorbox): 'tcbskinsjigsaw.code.tex' version '4.11'
))) (/usr/local/texlive/2017basic/texmf-dist/tex/latex/parskip/parskip.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.s
ty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.st
y)) (/usr/local/texlive/2017basic/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hxetex.

(/usr/local/texlive/2017basic/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)
)) (./JasonZukewichResume.aux) ABD: EverySelectfont initializing macros
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
ABD: EveryShipout initializing macros
(/usr/local/texlive/2017basic/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2017basic/texmf-dist/tex/generic/oberdiek/gettitlestring.st
y)) (./JasonZukewichResume.out) (./JasonZukewichResume.out)
Overfull \hbox (1.46pt too wide) in paragraph at lines 69--70
[]$[]$ $[]$$[]$

Underfull \hbox (badness 10000) in paragraph at lines 69--70

(./resume/skills.tex
Overfull \hbox (48.99248pt too wide) in alignment at lines 2--14
[] [] 
) (./resume/experience.tex) (./resume/projects.tex
Underfull \hbox (badness 6252) in paragraph at lines 18--18
[]\TU/SourceSansPro(1)/bx/n/10 DDR Step Genera-

Underfull \hbox (badness 10000) in paragraph at lines 18--18
[]\TU/SourceSansPro(1)/m/sc/8 Python, Scikit-Learn,

Overfull \hbox (55.14073pt too wide) in alignment at lines 2--51
[] [] 
) (./resume/education.tex [1]) [2] (./JasonZukewichResume.aux) )
(see the transcript file for additional information)
Output written on JasonZukewichResume.pdf (2 pages).
Transcript written on JasonZukewichResume.log.
